name: example
description: "Example of Ui Components"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  ui_components:
    path: ../

  localization:
    path:  ../../localization

dev_dependencies:
  dart_code_metrics_presets: 2.24.0

flutter:
  uses-material-design: true
